sudo: false
language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7
matrix:
  include:
    - go: 1.6.3
      script:
        - go get -t -sv ./...
        - go get -sv -race ./...
  fast_finish: true
before_install:
  - go get github.com/mattn/goveralls
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -sv ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -sv ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -sv -race ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
